apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-risk-backend
  namespace: ai-risk-generator
  labels:
    app: ai-risk-backend
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai-risk-backend
  template:
    metadata:
      labels:
        app: ai-risk-backend
        version: v1
    spec:
      containers:
      - name: backend
        image: ai-risk/backend:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ai-risk-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: ai-risk-secrets
              key: redis-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: ai-risk-secrets
              key: jwt-secret
        - name: ENCRYPTION_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: ai-risk-secrets
              key: encryption-key
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: ai-risk-secrets
              key: sentry-dsn
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL

---
apiVersion: v1
kind: Service
metadata:
  name: ai-risk-backend-service
  namespace: ai-risk-generator
spec:
  selector:
    app: ai-risk-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ai-risk-backend-hpa
  namespace: ai-risk-generator
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ai-risk-backend
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
