apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-risk-workers
  namespace: ai-risk-generator
  labels:
    app: ai-risk-workers
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-risk-workers
  template:
    metadata:
      labels:
        app: ai-risk-workers
        version: v1
    spec:
      containers:
      - name: workers
        image: ai-risk/workers:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ai-risk-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: ai-risk-secrets
              key: redis-url
        - name: NATS_URL
          valueFrom:
            secretKeyRef:
              name: ai-risk-secrets
              key: nats-url
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-risk-secrets
              key: openai-api-key
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-risk-secrets
              key: anthropic-api-key
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: ai-risk-secrets
              key: s3-access-key
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: ai-risk-secrets
              key: s3-secret-key
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000

---
apiVersion: v1
kind: Service
metadata:
  name: ai-risk-workers-service
  namespace: ai-risk-generator
spec:
  selector:
    app: ai-risk-workers
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ai-risk-workers-hpa
  namespace: ai-risk-generator
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ai-risk-workers
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85
